imports:
  - logging.yaml
  - model.yaml
  - training.yaml
  - dataset.yaml
  - runner.yaml

environment:
  seed: 42
  device: "cuda"

experiment:
  name: "image_baseline"
  work_dir: "work_dirs/experiments/image_baseline"
  tags:
    - "baseline"
    - "clinical_label"
  description: "Baseline model for breast MRI recurrance prediction"
