training:
  optimizer:
    name: "AdamW"
    params:
      lr: 0.0001
      betas: [0.9, 0.999]
      eps: 1e-8
      weight_decay: 0.03

  scheduler:
    name: "CosineAnnealingLR"
    params:
      T_max: 100
      eta_min: 1e-6

  loss:
    name: "focal_loss"
    params:
      alpha: [0.25, 0.5]
      gamma: 2.0
      reduction: "mean"

  grad_clip:
    enabled: true
    type: "norm"
    value: 1.0

  metrics:
    - accuracy
    - f1_score
    # - auc
