imports:
  - logging.yaml
  - model_add.yaml
  - training.yaml
  - dataset.yaml
  - runner.yaml

environment:
  seed: 42
  device: "cuda"

experiment:
  name: "multimodal_resnet3d_nphase_add"
  work_dir: "work_dirs/experiments/multimodal_resnet3d_nphase_add"
  tags:
    - "baseline"
    - "clinical_label"
  description: "Baseline model for breast MRI recurrance prediction"
