imports:
  - logging.yaml
  - model.yaml
  - training.yaml
  - dataset.yaml
  - runner.yaml

environment:
  seed: 42
  device: "cuda"

experiment:
  name: "recurrance_mri_baseline_dmodel_256_lr1e4"
  work_dir: "work_dirs/experiments/recurrance_mri_baseline_dmodel_256_lr1e4"
  tags:
    - "baseline"
    - "clinical_label"
  description: "Baseline model for breast MRI molecular subtype classification"
