model:
  name: multimodal_resnet3d_nphase_add #multimodal_resnet3d, multimodal_resnet3d_nphase
  params:
    n_classes: 2
    d_model: 256
    n_phases: 1
    out_dropout: 0.3
    backbone: resnet18
    pretrained: true
    pretrained_model: resnet3d_18_med3d
